### PR TITLE
Add GeomWithCachedEnvelope combinator to support memoizing envelope computations.

### LINKED ISSUE #108: Document in `RTreeObject` that `envelope()` should be cached
I've been testing inserting geometric objects into rstar. I noticed a ~20x speedup with some test data (300k `MultiPolygon`s) between inserting _geometries_ where `RTreeObject::envelope()` was implemented with a direct call to `bounding_rect` to inserting _wrapper structs_ that include both the geometry and a pre-cached envelope. This 20x speedup includes the time in the latter case to loop over the geometries and create each's envelope.

In retrospect, it's not too surprising that `envelope()` would need to be called multiple times, but I didn't see a mention of it on the [`RTreeObject`](https://docs.rs/rstar/latest/rstar/trait.RTreeObject.html) page.

### PR DESCRIPTION
**Pull request by adamreichold**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `rstar/CHANGELOG.md` if knowledge of this change could be valuable to users.

Closes #108

### CODE REVIEW

**Comment by adamreichold** [comment]
Personally, I am very much open to bike-shedding the name as I think `GeomWithCachedEnvelope` is a bit of a mouthful. Maybe just `CachedEnvelope`? The `geom` method could also be dropped entirely due to the `Deref` impl.

**Comment by rmanoka** [comment]
Nice, this is great.  Reg. the name:  we could also merge this func. into `GeomWithData<T::Envelope, T>` and add the `PointDist` impl.  We can then type alias it, and / or add a constructor `GeomWtihData::cached_envelope`.

Should we also add the explanation on why this is necessary somewhere more visible to most users?  Probably the `RTreeObject` trait or the main data-structure itself?

**Comment by urschrei** [comment]
> Should we also add the explanation on why this is necessary somewhere more visible to most users? Probably the RTreeObject trait or the main data-structure itself?

Yes, definitely. From the perspective of someone looking for a spatial index, it's currently not even obvious what rstar is for; that is, you have to know (or find out) what an R*-tree is. A light edit of the docs to make it a little clearer what's going on, and when to choose RTreeObject, GeomWithData, GeomWithCachedEnvelope would go a long way I think. We can do that in a follow-up PR.

**Review by rmanoka — APPROVED** [review]

**Comment by adamreichold** [comment]
> Nice, this is great. Reg. the name: we could also merge this func. into GeomWithData<T::Envelope, T> and add the PointDist impl. We can then type alias it, and / or add a constructor GeomWtihData::cached_envelope.

I admittedly do not follow. You mean using `GeomWithData` and store the envelope instead of the underlying geometry in `geom` and the geometry in `data`? How would the `PointDistance` impl decided whether to forward to `geom` or `data` in these circumstances? Wouldn't the impls overlap like

```console
error[E0119]: conflicting implementations of trait `object::PointDistance` for type `primitives::geom_with_data::GeomWithData<_, _>`
  --> rstar/src/primitives/geom_with_data.rs:69:1
   |
48 | impl<R: PointDistance, T> PointDistance for GeomWithData<R, T> {
   | -------------------------------------------------------------- first implementation here
...
69 | impl<T: PointDistance> PointDistance for GeomWithData<T::Envelope, T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `primitives::geom_with_data::GeomWithData<_, _>`
```

**Comment by rmanoka** [comment]
Yes, I didn't think about the point dist implementation properly.  So let's go with what you have; may be a shorter name if you find one.

**Comment by adamreichold** [comment]
> So let's go with what you have; may be a shorter name if you find one.

I'd propose just using `CachedEnvelope<T>`, i.e. dropping the `GeomWith` part and exclusively relying on `Deref` instead of a `geom` method. Agreed?

**Comment by adamreichold** [comment]
Merging since the shorter name seems uncontroversial and the code itself was previously approved.

**Comment by adamreichold** [comment]
Ouch, I totally forgot that we use bors here and merged manually for which I am sorry!

@urschrei I think it should be possible to prevent manual merges via the GitHub UI using the branch protection rules?

**Comment by urschrei** [comment]
Oh don't worry! I'll have a look at the settings.

**Pull request merged**
