### PR TITLE
Prepare for v0.10.0 release

### PR DESCRIPTION
**Pull request by urschrei**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `rstar/CHANGELOG.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
Sorry if you were waiting on review - LGTM!

**Comment by urschrei** [comment]
TY! Will merge and release tomorrow.

**Comment by rmanoka** [comment]
LGTM too.  I could publish it if @urschrei is occupied this week.  Pls lemme know.

**Comment by michaelkirk** [comment]
I went ahead and published this, it didn't seem like we were waiting on anything in particular.

Crate: https://crates.io/crates/rstar/0.10.0
Tag: https://github.com/georust/rstar/releases/tag/0.10.0

**Pull request merged**
