### PR TITLE
Release 0.9.2

### PR DESCRIPTION
**Pull request by rmanoka**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] ~I added an entry to `rstar/CHANGELOG.md` if knowledge of this change could be valuable to users.~
---

Preparing for release 0.9.2.   Could anyone take a quick look?

### CODE REVIEW

**Comment by rmanoka** [comment]
I'm just giving it a few days to see if there's any resolution to this PR in geo: https://github.com/georust/geo/pull/660

**Comment by rmanoka** [comment]
I don't think I can approve this, but all the changes lgtm!

**Review by urschrei — APPROVED** [review]
lgtm!

**Pull request merged**
