### PR TITLE
Fix clippy

### PR DESCRIPTION
**Pull request by jackson211**
fix all clippy warnings

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `rstar/CHANGELOG.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by rmanoka** [comment]
Nice 👍! Thanks!
Will give it a couple of days to see anyone has some related suggestions and merge o/w.

**Review by michaelkirk — APPROVED** [review]

**Comment by jackson211** [comment]
Looks like cargo-all-features

**Pull request merged**
